#!/bin/bash
if ! ps auxf | grep -q "[g]unicorn"; then
    echo "Gunicorn is not running, nothing to reload."
    exit 0
fi
echo "Gracefully shutting down some Gunicorn workers..."
kill -s TERM $(ps auxf | grep '[g]unicorn' | awk '{print $2}' | head -n 2)
echo "Starting new Gunicorn workers..."
gunicorn --workers 4 web_flask.0-hello_route:app &
echo "Gracefully shutting down remaining Gunicorn workers..."
kill -s TERM $(ps auxf | grep '[g]unicorn' | awk '{print $2}')
